module.exports = Object.freeze({
	INVALID_USER_NAME: 'INVALID_USER_NAME',
	INVALID_USER_ID: 'INVALID_USER_ID',
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	ALREADY_EXIST_USER_NAME: 'ALREADY_EXIST_USER_NAME',
	ATTACHMENTS_NOT_FOUND: 'ATTACHMENTS_NOT_FOUND',
	INVALID_OTP: 'INVALID_OTP',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	INVALID_SKILL_ID: 'INVALID_SKILL_ID',
	INVALID_CERTIFICATION_ID: 'INVALID_CERTIFICATION_ID',
	ACCESS_DENIED: 'ACCESS_DENIED',
})
