module.exports = Object.freeze({
    INVALID_USER_NAME: 'INVALID_USER_NAME',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ALREADY_EXIST_USER_NAME : 'ALREADY_EXIST_USER_NAME',
    DATABASE_ERROR : 'DATABASE_ERROR'


})
